# Generated by Django 5.2.6 on 2025-09-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('BCom', 'BCom'), ('BA', 'BA'), ('BTech', 'BTech'), ('MTech', 'MTech')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
